---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
    pre_build_image: true
  - name: bionic
    image: ubuntu:bionic
  - name: buster
    image: debian:buster
provisioner:
  name: ansible
verifier:
  name: ansible
